# Generated by Django 4.0 on 2022-01-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('income', models.IntegerField()),
                ('mobileNo', models.BigIntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
