# Generated by Django 4.0 on 2022-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
